// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for analyzing an order for potential fraud.
 *
 * The flow takes customer and order details as input and returns an AI-powered fraud analysis.
 * @param {OrderFraudCheckInput} input - The input to the fraud check flow.
 * @returns {Promise<OrderFraudCheckOutput>} - A promise that resolves to the fraud analysis.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

/**
 * Input schema for the order fraud check flow.
 */
export const OrderFraudCheckInputSchema = z.object({
  customer: z.object({
    name: z.string(),
    email: z.string(),
    phone: z.string(),
    ipAddress: z.string().describe('The IP address of the customer placing the order.'),
  }),
  order: z.object({
    total: z.number(),
    itemCount: z.number(),
  }),
});

/**
 * Type representing the input to the order fraud check flow.
 */
export type OrderFraudCheckInput = z.infer<typeof OrderFraudCheckInputSchema>;

/**
 * Output schema for the order fraud check flow.
 */
export const OrderFraudCheckOutputSchema = z.object({
  riskScore: z.number().describe('A risk score from 0 (low risk) to 100 (high risk).'),
  summary: z.string().describe('A brief summary of the fraud analysis.'),
  keyFactors: z.array(z.string()).describe('A list of key factors that influenced the risk score.'),
});

/**
 * Type representing the output of the order fraud check flow.
 */
export type OrderFraudCheckOutput = z.infer<typeof OrderFraudCheckOutputSchema>;


const fraudCheckPrompt = ai.definePrompt({
  name: 'fraudCheckPrompt',
  input: { schema: OrderFraudCheckInputSchema },
  output: { schema: OrderFraudCheckOutputSchema },
  prompt: `You are a fraud detection expert for an e-commerce store. Analyze the following order details and provide a fraud risk assessment.

  Customer Details:
  - Name: {{customer.name}}
  - Email: {{customer.email}}
  - Phone: {{customer.phone}}
  - IP Address: {{customer.ipAddress}}

  Order Details:
  - Order Total: $ {{order.total}}
  - Number of Items: {{order.itemCount}}
  
  Consider factors like:
  - Does the email look suspicious (e.g., temporary, gibberish)?
  - Is the order value unusually high for a new customer?
  - Does the IP address suggest the use of a proxy or VPN?
  - Any other patterns that seem indicative of fraud.

  Based on your analysis, provide a risk score from 0 to 100, a concise summary, and a list of key factors that contributed to your assessment.
  `,
});


/**
 * Genkit flow for performing an order fraud check.
 */
export const orderFraudCheckFlow = ai.defineFlow(
  {
    name: 'orderFraudCheckFlow',
    inputSchema: OrderFraudCheckInputSchema,
    outputSchema: OrderFraudCheckOutputSchema,
  },
  async (input) => {
    const { output } = await fraudCheckPrompt(input);
    return output!;
  }
);

/**
 * Wrapper function to be called from server actions.
 * @param input - The input data for the fraud check.
 * @returns The result of the fraud check flow.
 */
export async function performFraudCheck(input: OrderFraudCheckInput): Promise<OrderFraudCheckOutput> {
  return orderFraudCheckFlow(input);
}
