// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing product recommendations based on user browsing history.
 *
 * The flow takes a user's browsing history as input and returns a list of product recommendations.
 * @param {ProductRecommendationInput} input - The input to the product recommendation flow, including browsing history.
 * @returns {Promise<ProductRecommendationOutput>} - A promise that resolves to the product recommendations.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for the product recommendation flow.
 */
const ProductRecommendationInputSchema = z.object({
  browsingHistory: z
    .array(z.string())
    .describe('An array of product IDs representing the user browsing history.'),
});

/**
 * Type representing the input to the product recommendation flow.
 */
export type ProductRecommendationInput = z.infer<typeof ProductRecommendationInputSchema>;

/**
 * Output schema for the product recommendation flow.
 */
const ProductRecommendationOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe('An array of product IDs representing the product recommendations.'),
});

/**
 * Type representing the output of the product recommendation flow.
 */
export type ProductRecommendationOutput = z.infer<typeof ProductRecommendationOutputSchema>;

/**
 * Async function to get product recommendations.
 * @param input - Browsing history to generate product recommendations.
 * @returns The product recommendations.
 */
export async function getProductRecommendations(input: ProductRecommendationInput): Promise<ProductRecommendationOutput> {
  return productRecommendationFlow(input);
}

const productRecommendationPrompt = ai.definePrompt({
  name: 'productRecommendationPrompt',
  input: {schema: ProductRecommendationInputSchema},
  output: {schema: ProductRecommendationOutputSchema},
  prompt: `You are a product recommendation expert. Given a user's browsing history, you will recommend products that the user might be interested in.

  Browsing History: {{browsingHistory}}

  Recommendations:`,
});

/**
 * Genkit flow for product recommendations.
 */
const productRecommendationFlow = ai.defineFlow(
  {
    name: 'productRecommendationFlow',
    inputSchema: ProductRecommendationInputSchema,
    outputSchema: ProductRecommendationOutputSchema,
  },
  async input => {
    const {output} = await productRecommendationPrompt(input);
    return output!;
  }
);
