import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Aura Headphones',
    description: 'High-fidelity wireless headphones with noise-cancellation. Immersive sound in a sleek, modern design.',
    price: 249.99,
    image: 'https://picsum.photos/seed/aura/600/400',
    category: 'Electronics',
    colors: ['#343a40', '#f8f9fa', '#9D4EDD'],
    variants: [{ name: 'Standard' }, { name: 'Pro', priceModifier: 50 }],
    popularity: 95,
  },
  {
    id: '2',
    name: 'ChromaBloom Vase',
    description: 'A minimalist ceramic vase that adds a pop of color to any room. Perfect for single stems or small bouquets.',
    price: 45.0,
    image: 'https://picsum.photos/seed/chroma/600/400',
    category: 'Home & Living',
    colors: ['#E9D5FF', '#ffffff', '#5A86FF'],
    sizes: ['Small', 'Medium', 'Large'],
    popularity: 88,
  },
  {
    id: '3',
    name: 'Spectrum Tee',
    description: 'A comfortable, 100% organic cotton t-shirt with a subtle, embroidered color spectrum logo.',
    price: 35.5,
    image: 'https://picsum.photos/seed/spectrum/600/400',
    category: 'Fashion',
    colors: ['#212529', '#ffffff', '#ced4da'],
    sizes: ['S', 'M', 'L', 'XL'],
    popularity: 92,
  },
  {
    id: '4',
    name: 'Kinetic Desk Lamp',
    description: 'A smart desk lamp with adjustable color temperature and brightness. Control it via app or touch.',
    price: 120.0,
    image: 'https://picsum.photos/seed/kinetic/600/400',
    category: 'Electronics',
    colors: ['#adb5bd', '#343a40'],
    popularity: 85,
  },
  {
    id: '5',
    name: 'Nova Smartwatch',
    description: 'Track your fitness and stay connected with the Nova Smartwatch. Features a vibrant, customizable display.',
    price: 199.5,
    image: 'https://picsum.photos/seed/nova/600/400',
    category: 'Electronics',
    colors: ['#343a40', '#9D4EDD', '#5A86FF'],
    variants: [
      { name: 'Standard' },
      { name: 'Titanium', priceModifier: 80 },
    ],
    popularity: 98,
  },
  {
    id: '6',
    name: 'Flow Yoga Mat',
    description: 'A durable, non-slip yoga mat made from eco-friendly materials. Your perfect partner for mindfulness.',
    price: 65.0,
    image: 'https://picsum.photos/seed/flow/600/400',
    category: 'Health & Beauty',
    colors: ['#9D4EDD', '#5A86FF', '#E9D5FF'],
    popularity: 78,
  },
  {
    id: '7',
    name: 'Gradient Mug',
    description: 'Start your day with a splash of color. This ceramic mug features a beautiful gradient finish.',
    price: 22.0,
    image: 'https://picsum.photos/seed/gradient/600/400',
    category: 'Home & Living',
    colors: ['#9D4EDD', '#5A86FF'],
    popularity: 91,
  },
  {
    id: '8',
    name: 'Orbit Wall Clock',
    description: 'A modern, silent wall clock with a minimalist design. Tells time without the ticking.',
    price: 75.0,
    image: 'https://picsum.photos/seed/orbit/600/400',
    category: 'Home & Living',
    colors: ['#212529', '#f8f9fa', '#5A86FF'],
    popularity: 80,
  },
  {
    id: '9',
    name: 'Hue Ambient Light',
    description: 'Set the mood with this smart ambient light. Choose from millions of colors to create the perfect atmosphere.',
    price: 89.99,
    image: 'https://picsum.photos/seed/hue/600/400',
    category: 'Electronics',
    colors: ['#ffffff'],
    popularity: 96,
  },
  {
    id: '10',
    name: 'Crisp White Sneakers',
    description: 'Versatile and stylish sneakers that pair with any outfit. Made with premium, sustainable materials.',
    price: 135.0,
    image: 'https://picsum.photos/seed/sneakers/600/400',
    category: 'Fashion',
    colors: ['#ffffff', '#f8f9fa'],
    sizes: ['8', '9', '10', '11', '12'],
    popularity: 89,
  },
  {
    id: '11',
    name: 'Aero Backpack',
    description: 'A sleek, water-resistant backpack for your daily commute or weekend adventures. Padded laptop sleeve included.',
    price: 110.0,
    image: 'https://picsum.photos/seed/aero/600/400',
    category: 'Fashion',
    colors: ['#343a40', '#495057'],
    popularity: 93,
  },
  {
    id: '12',
    name: 'Plush Throw Blanket',
    description: 'Get cozy with this incredibly soft throw blanket. Perfect for movie nights on the couch.',
    price: 55.0,
    image: 'https://picsum.photos/seed/plush/600/400',
    category: 'Home & Living',
    colors: ['#E9D5FF', '#ced4da'],
    sizes: ['Standard', 'King'],
    popularity: 84,
  },
  {
    id: '13',
    name: 'Gourmet Coffee Beans',
    description: 'Start your day right with our ethically sourced, single-origin Arabica coffee beans. Rich and aromatic.',
    price: 18.5,
    image: 'https://picsum.photos/seed/coffee/600/400',
    category: 'Groceries',
    colors: ['#6f4e37'],
    popularity: 87,
  },
  {
    id: '14',
    name: 'Artisanal Olive Oil',
    description: 'Cold-pressed extra virgin olive oil from heritage groves. Perfect for dressings and finishing dishes.',
    price: 25.0,
    image: 'https://picsum.photos/seed/oil/600/400',
    category: 'Groceries',
    colors: ['#e4d59a'],
    popularity: 76,
  },
  {
    id: '15',
    name: 'Organic Face Serum',
    description: 'A rejuvenating face serum packed with antioxidants to hydrate and brighten your skin naturally.',
    price: 42.0,
    image: 'https://picsum.photos/seed/serum/600/400',
    category: 'Health & Beauty',
    colors: ['#fdebd0'],
    popularity: 81,
  },
  {
    id: '16',
    name: 'Zen Garden Incense Kit',
    description: 'Create a tranquil space with our incense kit, featuring sandalwood sticks and a ceramic holder.',
    price: 30.0,
    image: 'https://picsum.photos/seed/zen/600/400',
    category: 'Health & Beauty',
    colors: ['#d1ccc3', '#8b8589'],
    popularity: 72,
  },
];
