import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Aura Headphones',
    description: 'High-fidelity wireless headphones with noise-cancellation. Immersive sound in a sleek, modern design.',
    price: 249.99,
    image: 'https://picsum.photos/seed/aura/600/400',
    category: 'Tech',
    colors: ['#343a40', '#f8f9fa', '#9D4EDD'],
    popularity: 95,
  },
  {
    id: '2',
    name: 'ChromaBloom Vase',
    description: 'A minimalist ceramic vase that adds a pop of color to any room. Perfect for single stems or small bouquets.',
    price: 45.0,
    image: 'https://picsum.photos/seed/chroma/600/400',
    category: 'Home',
    colors: ['#E9D5FF', '#ffffff', '#5A86FF'],
    popularity: 88,
  },
  {
    id: '3',
    name: 'Spectrum Tee',
    description: 'A comfortable, 100% organic cotton t-shirt with a subtle, embroidered color spectrum logo.',
    price: 35.5,
    image: 'https://picsum.photos/seed/spectrum/600/400',
    category: 'Apparel',
    colors: ['#212529', '#ffffff', '#ced4da'],
    popularity: 92,
  },
  {
    id: '4',
    name: 'Kinetic Desk Lamp',
    description: 'A smart desk lamp with adjustable color temperature and brightness. Control it via app or touch.',
    price: 120.0,
    image: 'https://picsum.photos/seed/kinetic/600/400',
    category: 'Tech',
    colors: ['#adb5bd', '#343a40'],
    popularity: 85,
  },
  {
    id: '5',
    name: 'Nova Smartwatch',
    description: 'Track your fitness and stay connected with the Nova Smartwatch. Features a vibrant, customizable display.',
    price: 199.5,
    image: 'https://picsum.photos/seed/nova/600/400',
    category: 'Tech',
    colors: ['#343a40', '#9D4EDD', '#5A86FF'],
    popularity: 98,
  },
  {
    id: '6',
    name: 'Flow Yoga Mat',
    description: 'A durable, non-slip yoga mat made from eco-friendly materials. Your perfect partner for mindfulness.',
    price: 65.0,
    image: 'https://picsum.photos/seed/flow/600/400',
    category: 'Lifestyle',
    colors: ['#9D4EDD', '#5A86FF', '#E9D5FF'],
    popularity: 78,
  },
  {
    id: '7',
    name: 'Gradient Mug',
    description: 'Start your day with a splash of color. This ceramic mug features a beautiful gradient finish.',
    price: 22.0,
    image: 'https://picsum.photos/seed/gradient/600/400',
    category: 'Home',
    colors: ['#9D4EDD', '#5A86FF'],
    popularity: 91,
  },
  {
    id: '8',
    name: 'Orbit Wall Clock',
    description: 'A modern, silent wall clock with a minimalist design. Tells time without the ticking.',
    price: 75.0,
    image: 'https://picsum.photos/seed/orbit/600/400',
    category: 'Home',
    colors: ['#212529', '#f8f9fa', '#5A86FF'],
    popularity: 80,
  },
  {
    id: '9',
    name: 'Hue Ambient Light',
    description: 'Set the mood with this smart ambient light. Choose from millions of colors to create the perfect atmosphere.',
    price: 89.99,
    image: 'https://picsum.photos/seed/hue/600/400',
    category: 'Tech',
    colors: ['#ffffff'],
    popularity: 96,
  },
  {
    id: '10',
    name: 'Crisp White Sneakers',
    description: 'Versatile and stylish sneakers that pair with any outfit. Made with premium, sustainable materials.',
    price: 135.0,
    image: 'https://picsum.photos/seed/sneakers/600/400',
    category: 'Apparel',
    colors: ['#ffffff', '#f8f9fa'],
    popularity: 89,
  },
  {
    id: '11',
    name: 'Aero Backpack',
    description: 'A sleek, water-resistant backpack for your daily commute or weekend adventures. Padded laptop sleeve included.',
    price: 110.0,
    image: 'https://picsum.photos/seed/aero/600/400',
    category: 'Lifestyle',
    colors: ['#343a40', '#495057'],
    popularity: 93,
  },
  {
    id: '12',
    name: 'Plush Throw Blanket',
    description: 'Get cozy with this incredibly soft throw blanket. Perfect for movie nights on the couch.',
    price: 55.0,
    image: 'https://picsum.photos/seed/plush/600/400',
    category: 'Home',
    colors: ['#E9D5FF', '#ced4da'],
    popularity: 84,
  },
];
