// This is an autogenerated file from Firebase Studio.

'use server';

import { collection, addDoc, Timestamp } from 'firebase/firestore';
import { headers } from 'next/headers';
import { db } from '@/lib/firebase';
import type { CartItem, Order } from '@/lib/types';
import { performFraudCheck } from '@/ai/flows/order-fraud-check';

interface GuestDetails {
  name: string;
  email: string;
  phone: string;
  address: string;
}

export async function createOrder(guestDetails: GuestDetails, cart: CartItem[], total: number) {
  try {
    const headersList = headers();
    const ipAddress = headersList.get('x-forwarded-for') || '127.0.0.1';
    
    // 1. Perform AI Fraud Analysis
    const aiAnalysis = await performFraudCheck({
      customer: {
        name: guestDetails.name,
        email: guestDetails.email,
        phone: guestDetails.phone,
        ipAddress: ipAddress,
      },
      order: {
        total: total,
        itemCount: cart.reduce((sum, item) => sum + item.quantity, 0),
      }
    });

    // 2. Create the order object
    const orderData: Omit<Order, 'id'> = {
      orderDate: Timestamp.now(),
      customer: {
        name: guestDetails.name,
        email: guestDetails.email,
        phone: guestDetails.phone,
        ipAddress: ipAddress,
        location: guestDetails.address,
      },
      items: cart,
      total: total,
      status: 'Completed', // Assuming demo payment is always successful
      paymentMethod: 'Demo Payment',
      aiAnalysis: aiAnalysis,
    };

    // 3. Save the order to Firestore
    const docRef = await addDoc(collection(db, 'orders'), orderData);

    // 4. Return the new order ID and the full order data
    return {
        success: true,
        orderId: docRef.id,
        order: { ...orderData, id: docRef.id, orderDate: new Date() } // Return with JS Date object
    };

  } catch (error) {
    console.error("Error creating order: ", error);
    return { success: false, error: 'Failed to create order.' };
  }
}
